/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/zyhRMoOrH0D
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Gabarito } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

gabarito({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export function AboutUs() {
	return (
		<div className="flex flex-col min-h-[100dvh]">
			<main className="flex-1">
				<section id="mission" className="py-12 md:py-24 bg-background">
					<div className="container mx-auto px-4 md:px-6">
						<div className="grid md:grid-cols-2 gap-8">
							<div>
								<h2 className="text-3xl font-bold mb-4">
									Our Mission
								</h2>
								<p className="text-muted-foreground leading-relaxed">
									At Acme Nonprofit, our mission is to create
									a more equitable and sustainable world by
									empowering communities and advocating for
									social justice. We believe that every
									individual deserves access to the resources
									and opportunities they need to thrive, and
									we are dedicated to making that a reality.
								</p>
								<p className="text-muted-foreground leading-relaxed mt-4">
									Through our various programs and
									initiatives, we work tirelessly to address
									the root causes of societal challenges, such
									as poverty, education inequality, and
									environmental degradation. Our team of
									passionate professionals is committed to
									driving meaningful change and creating a
									brighter future for all.
								</p>
							</div>
							<div>
								<h2 className="text-3xl font-bold mb-4">
									Our Vision
								</h2>
								<p className="text-muted-foreground leading-relaxed">
									Our vision is a world where every person has
									the opportunity to reach their full
									potential, regardless of their background or
									circumstances. We envision a future where
									communities are empowered, resources are
									equitably distributed, and the environment
									is protected for generations to come.
								</p>
								<p className="text-muted-foreground leading-relaxed mt-4">
									By fostering collaboration, innovation, and
									a deep commitment to social impact, we are
									working to make this vision a reality. We
									believe that together, we can create a more
									just, inclusive, and sustainable world for
									all.
								</p>
							</div>
						</div>
					</div>
				</section>
				<section id="team" className="py-12 md:py-24 bg-muted">
					<div className="container mx-auto px-4 md:px-6">
						<h2 className="text-3xl font-bold mb-8 text-center">
							Our Team
						</h2>
						<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
							<div className="bg-background rounded-lg overflow-hidden shadow-md">
								<img
									src="/placeholder.svg"
									width={400}
									height={400}
									alt="John Doe"
									className="w-full h-48 object-cover"
									style={{
										aspectRatio: "400/400",
										objectFit: "cover",
									}}
								/>
								<div className="p-4">
									<h3 className="text-xl font-bold">
										John Doe
									</h3>
									<p className="text-muted-foreground">
										Executive Director
									</p>
									<p className="text-muted-foreground mt-2">
										John has over 15 years of experience in
										the nonprofit sector, with a proven
										track record of driving positive change
										in local communities.
									</p>
								</div>
							</div>
							<div className="bg-background rounded-lg overflow-hidden shadow-md">
								<img
									src="/placeholder.svg"
									width={400}
									height={400}
									alt="Jane Smith"
									className="w-full h-48 object-cover"
									style={{
										aspectRatio: "400/400",
										objectFit: "cover",
									}}
								/>
								<div className="p-4">
									<h3 className="text-xl font-bold">
										Jane Smith
									</h3>
									<p className="text-muted-foreground">
										Program Manager
									</p>
									<p className="text-muted-foreground mt-2">
										Jane has a deep passion for community
										development and has been instrumental in
										the success of our outreach initiatives.
									</p>
								</div>
							</div>
							<div className="bg-background rounded-lg overflow-hidden shadow-md">
								<img
									src="/placeholder.svg"
									width={400}
									height={400}
									alt="Michael Johnson"
									className="w-full h-48 object-cover"
									style={{
										aspectRatio: "400/400",
										objectFit: "cover",
									}}
								/>
								<div className="p-4">
									<h3 className="text-xl font-bold">
										Michael Johnson
									</h3>
									<p className="text-muted-foreground">
										Volunteer Coordinator
									</p>
									<p className="text-muted-foreground mt-2">
										Michael&apos;s dedication to building
										strong volunteer networks has been
										invaluable in expanding our reach and
										impact.
									</p>
								</div>
							</div>
						</div>
						<div className="mt-8">
							<img
								src="/placeholder.svg"
								alt="Our Team"
								width={1200}
								height={600}
								className="w-full rounded-lg object-cover"
								style={{
									aspectRatio: "1200/600",
									objectFit: "cover",
								}}
							/>
						</div>
					</div>
				</section>
				<section id="contact" className="py-12 md:py-24 bg-white">
					<div className="container mx-auto px-4 md:px-6">
						<h2 className="text-3xl font-bold mb-8 text-center">
							Contact Us
						</h2>
						<div className="grid md:grid-cols-2 gap-8">
							<div>
								<h3 className="text-xl font-bold mb-4">
									Get in Touch
								</h3>
								<p className="text-muted-foreground leading-relaxed">
									We&apos;d love to hear from you! Whether you
									have a question, feedback, or are interested
									in supporting our work, please don&apos;t
									hesitate to reach out.
								</p>
								<div className="mt-6 space-y-4">
									<div className="flex items-center gap-2">
										<MailIcon className="h-5 w-5 text-muted-foreground" />
										<a
											href="#"
											className="text-muted-foreground hover:underline"
										>
											info@acmenonprofit.org
										</a>
									</div>
									<div className="flex items-center gap-2">
										<PhoneIcon className="h-5 w-5 text-muted-foreground" />
										<a
											href="#"
											className="text-muted-foreground hover:underline"
										>
											+1 (234) 567-890
										</a>
									</div>
								</div>
							</div>
							<div>
								<h3 className="text-xl font-bold mb-4">
									Contact Form
								</h3>
								<form className="space-y-4">
									<Input
										type="text"
										placeholder="Name"
										className="w-full"
									/>
									<Input
										type="email"
										placeholder="Email"
										className="w-full"
									/>
									<Textarea
										placeholder="Message"
										className="w-full"
										rows={5}
									/>
									<Button type="submit">Submit</Button>
								</form>
							</div>
						</div>
					</div>
				</section>
				<section id="reports" className="py-12 md:py-24 bg-muted">
					<div className="container mx-auto px-4 md:px-6">
						<h2 className="text-3xl font-bold mb-8 text-center">
							Annual Reports
						</h2>
						<div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-8">
							<div className="bg-background rounded-lg overflow-hidden shadow-md">
								<div className="p-4">
									<h3 className="text-xl font-bold">
										2022 Annual Report
									</h3>
									<p className="text-muted-foreground mt-2">
										Download our 2022 annual report to learn
										more about our impact and financial
										performance.
									</p>
									<div className="mt-4">
										<Link
											href="#"
											className="inline-flex items-center gap-2 text-primary hover:underline"
											download
											prefetch={false}
										>
											<DownloadIcon className="h-5 w-5" />
											Download
										</Link>
									</div>
								</div>
							</div>
							<div className="bg-background rounded-lg overflow-hidden shadow-md">
								<div className="p-4">
									<h3 className="text-xl font-bold">
										2021 Annual Report
									</h3>
									<p className="text-muted-foreground mt-2">
										Check out our 2021 annual report to see
										how we&apos;ve been making a difference
										in our community.
									</p>
									<div className="mt-4">
										<Link
											href="#"
											className="inline-flex items-center gap-2 text-primary hover:underline"
											download
											prefetch={false}
										>
											<DownloadIcon className="h-5 w-5" />
											Download
										</Link>
									</div>
								</div>
							</div>
							<div className="bg-background rounded-lg overflow-hidden shadow-md">
								<div className="p-4">
									<h3 className="text-xl font-bold">
										2020 Annual Report
									</h3>
									<p className="text-muted-foreground mt-2">
										Explore our 2020 annual report to learn
										about our achievements and financial
										performance.
									</p>
									<div className="mt-4">
										<Link
											href="#"
											className="inline-flex items-center gap-2 text-primary hover:underline"
											download
											prefetch={false}
										>
											<DownloadIcon className="h-5 w-5" />
											Download
										</Link>
									</div>
								</div>
							</div>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}

function DownloadIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
			<polyline points="7 10 12 15 17 10" />
			<line x1="12" x2="12" y1="15" y2="3" />
		</svg>
	);
}

function MailIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<rect width="20" height="16" x="2" y="4" rx="2" />
			<path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
		</svg>
	);
}

function MenuIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<line x1="4" x2="20" y1="12" y2="12" />
			<line x1="4" x2="20" y1="6" y2="6" />
			<line x1="4" x2="20" y1="18" y2="18" />
		</svg>
	);
}

function PhoneIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
		</svg>
	);
}
