"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gs4SGybnYSs
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
	Carousel,
	CarouselContent,
	CarouselItem,
	CarouselPrevious,
	CarouselNext,
	CarouselApi,
} from "@/components/ui/carousel";
import Link from "next/link";
import React from "react";
import Autoplay from "embla-carousel-autoplay";

export function ActivitiesCarousel() {
	const [api, setApi] = React.useState<CarouselApi>();

	return (
		<section className="w-full py-6 md:py-12 lg:py-16">
			<div className="container px-4 md:px-6 space-y-8">
				<div className="text-center space-y-4">
					<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
						Empowering Our Community
					</h2>
					<p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
						Discover the diverse initiatives and programs of our
						non-profit organization as we strive to make a positive
						impact in our community.
					</p>
				</div>
				<Carousel
					className="w-full max-w-4xl mx-auto"
					opts={{
						loop: true,
					}}
					plugins={[
						Autoplay({
							delay: 3000,
						}),
					]}
					setApi={setApi}
				>
					<CarouselContent>
						<CarouselItem>
							<div className="grid md:grid-cols-2 gap-6">
								<img
									src="/placeholder.svg"
									width={600}
									height={400}
									alt="Mentorship Program"
									className="rounded-md object-cover aspect-[3/2]"
								/>
								<div className="space-y-4">
									<h3 className="text-2xl font-bold">
										Mentorship Program
									</h3>
									<p className="text-muted-foreground">
										Our mentorship program pairs
										underprivileged youth with experienced
										professionals to help them develop
										essential life and career skills.
									</p>
									<Link
										href="#"
										className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
										prefetch={false}
									>
										Learn More
									</Link>
								</div>
							</div>
						</CarouselItem>
						<CarouselItem>
							<div className="grid md:grid-cols-2 gap-6">
								<img
									src="/placeholder.svg"
									width={600}
									height={400}
									alt="Community Cleanup"
									className="rounded-md object-cover aspect-[3/2]"
								/>
								<div className="space-y-4">
									<h3 className="text-2xl font-bold">
										Community Cleanup
									</h3>
									<p className="text-muted-foreground">
										Join us in our monthly community cleanup
										events to help keep our neighborhoods
										clean and green.
									</p>
									<Link
										href="#"
										className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
										prefetch={false}
									>
										Get Involved
									</Link>
								</div>
							</div>
						</CarouselItem>
						<CarouselItem>
							<div className="grid md:grid-cols-2 gap-6">
								<img
									src="/placeholder.svg"
									width={600}
									height={400}
									alt="Food Drive"
									className="rounded-md object-cover aspect-[3/2]"
								/>
								<div className="space-y-4">
									<h3 className="text-2xl font-bold">
										Food Drive
									</h3>
									<p className="text-muted-foreground">
										Help us stock the shelves of our local
										food bank by donating non-perishable
										items during our quarterly food drives.
									</p>
									<Link
										href="#"
										className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
										prefetch={false}
									>
										Donate Now
									</Link>
								</div>
							</div>
						</CarouselItem>
					</CarouselContent>
					<CarouselPrevious />
					<CarouselNext />
				</Carousel>
			</div>
		</section>
	);
}
