/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/mw75kymJCWj
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Link } from "lucide-react";

export function CommunityCards() {
	return (
		<div className="w-full py-6">
			<section className=" md:py-20 lg:py-28">
				<div className="container">
					<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mt-12">
						<div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-all duration-300">
							<Sheet>
								<SheetTrigger asChild>
									<div className="aspect-[4/3] bg-[url('/placeholder.svg?height=400&width=600')] bg-cover bg-center group-hover:scale-105 transition-transform duration-300">
										<div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex items-end p-6">
											<div className="space-y-2 text-white">
												<h3 className="text-2xl font-bold">
													Indigenous Communities
												</h3>
												<p className="text-sm">
													Empowering and supporting
													indigenous communities
													worldwide.
												</p>
											</div>
										</div>
									</div>
								</SheetTrigger>
								<SheetContent
									side="right"
									className="w-[400px] max-w-full"
								>
									<div className="p-6 space-y-4">
										<div className="space-y-2">
											<h3 className="text-2xl font-bold">
												Indigenous Communities
											</h3>
											<p className="text-muted-foreground">
												We work closely with indigenous
												communities around the world to
												provide resources, education,
												and support. Our goal is to
												empower these communities and
												preserve their rich cultural
												heritage.
											</p>
										</div>
										<div className="space-y-2">
											<h4 className="text-lg font-semibold">
												Key Initiatives
											</h4>
											<ul className="space-y-1 text-muted-foreground">
												<li>
													- Sustainable agriculture
													and land management programs
												</li>
												<li>
													- Educational scholarships
													and vocational training
												</li>
												<li>
													- Cultural preservation and
													revitalization projects
												</li>
												<li>
													- Advocacy for indigenous
													rights and
													self-determination
												</li>
											</ul>
										</div>
										<div className="space-y-2">
											<h4 className="text-lg font-semibold">
												Get Involved
											</h4>
											<p className="text-muted-foreground">
												Learn more about how you can
												support our work with indigenous
												communities.
											</p>
											<Button variant="outline">
												<a href="/communities/indigenous">
													View Community
												</a>
											</Button>
										</div>
									</div>
								</SheetContent>
							</Sheet>
						</div>
						<div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-all duration-300">
							<Sheet>
								<SheetTrigger asChild>
									<div className="aspect-[4/3] bg-[url('/placeholder.svg?height=400&width=600')] bg-cover bg-center group-hover:scale-105 transition-transform duration-300">
										<div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex items-end p-6">
											<div className="space-y-2 text-white">
												<h3 className="text-2xl font-bold">
													Refugee Communities
												</h3>
												<p className="text-sm">
													Supporting displaced
													individuals and families
													worldwide.
												</p>
											</div>
										</div>
									</div>
								</SheetTrigger>
								<SheetContent
									side="right"
									className="w-[400px] max-w-full"
								>
									<div className="p-6 space-y-4">
										<div className="space-y-2">
											<h3 className="text-2xl font-bold">
												Refugee Communities
											</h3>
											<p className="text-muted-foreground">
												We are committed to supporting
												refugee communities around the
												world. Our programs focus on
												providing essential services,
												education, and opportunities for
												displaced individuals and
												families to rebuild their lives.
											</p>
										</div>
										<div className="space-y-2">
											<h4 className="text-lg font-semibold">
												Key Initiatives
											</h4>
											<ul className="space-y-1 text-muted-foreground">
												<li>
													- Emergency relief and
													humanitarian aid
												</li>
												<li>
													- Language classes and
													vocational training
												</li>
												<li>
													- Mental health and
													counseling services
												</li>
												<li>
													- Resettlement assistance
													and integration support
												</li>
											</ul>
										</div>
										<div className="space-y-2">
											<h4 className="text-lg font-semibold">
												Get Involved
											</h4>
											<p className="text-muted-foreground">
												Learn more about how you can
												support our work with refugee
												communities.
											</p>
											<Button variant="outline">
												Explore Opportunities
											</Button>
										</div>
									</div>
								</SheetContent>
							</Sheet>
						</div>
						<div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-all duration-300">
							<Sheet>
								<SheetTrigger asChild>
									<div className="aspect-[4/3] bg-[url('/placeholder.svg?height=400&width=600')] bg-cover bg-center group-hover:scale-105 transition-transform duration-300">
										<div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex items-end p-6">
											<div className="space-y-2 text-white">
												<h3 className="text-2xl font-bold">
													Youth Communities
												</h3>
												<p className="text-sm">
													Empowering and supporting
													young people to reach their
													full potential.
												</p>
											</div>
										</div>
									</div>
								</SheetTrigger>
								<SheetContent
									side="right"
									className="w-[400px] max-w-full"
								>
									<div className="p-6 space-y-4">
										<div className="space-y-2">
											<h3 className="text-2xl font-bold">
												Youth Communities
											</h3>
											<p className="text-muted-foreground">
												Our organization is dedicated to
												supporting and empowering young
												people from diverse backgrounds.
												We offer a range of programs and
												initiatives to help them develop
												their skills, pursue their
												dreams, and make a positive
												impact in their communities.
											</p>
										</div>
										<div className="space-y-2">
											<h4 className="text-lg font-semibold">
												Key Initiatives
											</h4>
											<ul className="space-y-1 text-muted-foreground">
												<li>
													- Mentorship and leadership
													development programs
												</li>
												<li>
													- Entrepreneurship and job
													skills training
												</li>
												<li>
													- Scholarships and
													educational support
												</li>
												<li>
													- Community service and
													volunteering opportunities
												</li>
											</ul>
										</div>
										<div className="space-y-2">
											<h4 className="text-lg font-semibold">
												Get Involved
											</h4>
											<p className="text-muted-foreground">
												Learn more about how you can
												support our work with youth
												communities.
											</p>
											<Button variant="outline">
												Explore Opportunities
											</Button>
										</div>
									</div>
								</SheetContent>
							</Sheet>
						</div>
						<div className="group relative overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-all duration-300">
							<Sheet>
								<SheetTrigger asChild>
									<div className="aspect-[4/3] bg-[url('/placeholder.svg?height=400&width=600')] bg-cover bg-center group-hover:scale-105 transition-transform duration-300">
										<div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent flex items-end p-6">
											<div className="space-y-2 text-white">
												<h3 className="text-2xl font-bold">
													Disability Communities
												</h3>
												<p className="text-sm">
													Advocating for and
													supporting individuals with
													disabilities.
												</p>
											</div>
										</div>
									</div>
								</SheetTrigger>
								<SheetContent
									side="right"
									className="w-[400px] max-w-full"
								>
									<div className="p-6 space-y-4">
										<div className="space-y-2">
											<h3 className="text-2xl font-bold">
												Disability Communities
											</h3>
											<p className="text-muted-foreground">
												Inclusion and accessibility are
												at the heart of our work with
												disability communities. We
												strive to empower individuals
												with disabilities and advocate
												for their rights and equal
												opportunities.
											</p>
										</div>
										<div className="space-y-2">
											<h4 className="text-lg font-semibold">
												Key Initiatives
											</h4>
											<ul className="space-y-1 text-muted-foreground">
												<li>
													- Assistive technology and
													accessibility programs
												</li>
												<li>
													- Inclusive education and
													employment initiatives
												</li>
												<li>
													- Advocacy for disability
													rights and policy changes
												</li>
												<li>
													- Community-based support
													and social services
												</li>
											</ul>
										</div>
										<div className="space-y-2">
											<h4 className="text-lg font-semibold">
												Get Involved
											</h4>
											<p className="text-muted-foreground">
												Learn more about how you can
												support our work with disability
												communities.
											</p>
											<Button variant="outline">
												Explore Opportunities
											</Button>
										</div>
									</div>
								</SheetContent>
							</Sheet>
						</div>
					</div>
				</div>
			</section>
		</div>
	);
}
