/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aL1OjRmoKAa
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Eczar } from 'next/font/google'
import { Yeseva_One } from 'next/font/google'

eczar({
  subsets: ['latin'],
  display: 'swap',
})

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import {
	Card,
	CardHeader,
	CardTitle,
	CardContent,
	CardFooter,
} from "@/components/ui/card";
import Link from "next/link";
import { Timeline, TimelineItem } from "./timeline";
import { JSX, SVGProps } from "react";

export function Community() {
	const timelineItems: TimelineItem[] = [
		{
			icon: null,
			title: "Community Center Established",
			date: new Date("1972"),
			description:
				"The community center was founded in 1972 to serve as a hub for local residents.",
		},
		{
			icon: null,
			title: "Expansion of Facilities",
			date: new Date("1985"),
			description:
				"In 1985, the center underwent a major expansion to include a library, gymnasium, and additional classrooms.",
		},
		{
			icon: null,
			title: "Renovation and Modernization",
			date: new Date("2010"),
			description:
				"The facilities underwent a comprehensive renovation in 2010 to modernize the infrastructure and improve accessibility.",
		},
		{
			icon: null,
			title: "First Large Scale Event",
			date: new Date("2015"),
			description:
				"The community center hosted its first large-scale event, bringing together residents, volunteers, and local leaders.",
		},
	];

	return (
		<div className="w-full">
			<section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
				<div className="container px-4 md:px-6">
					<div className="flex flex-col items-center justify-center space-y-4 text-center">
						<div className="space-y-2">
							<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
								Langa
							</h2>
							<p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
								Give a short description of the community and
								the work that is being done there. Highlight the
								key areas of focus and the impact that the
								community center has had on the residents.
							</p>
						</div>
					</div>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32">
				<div className="container px-4 md:px-6">
					<div className="grid gap-6 lg:grid-cols-1 lg:gap-12">
						<div>
							<h3 className="text-2xl font-bold tracking-tighter mb-4">
								History of the Facilities
							</h3>
							<div className="rounded-lg bg-muted p-6">
								<Timeline items={timelineItems} />
							</div>
						</div>
						<div>
							<h3 className="text-2xl font-bold tracking-tighter mb-4">
								Community Legends
							</h3>
							<div className="grid grid-cols-2 gap-4">
								<div className="bg-muted rounded-lg p-4 flex flex-col items-center text-center">
									<Avatar className="w-16 h-16 mb-2">
										<AvatarImage
											src="/placeholder-user.jpg"
											alt="John Doe"
										/>
										<AvatarFallback>JD</AvatarFallback>
									</Avatar>
									<h4 className="text-lg font-semibold">
										John Doe
									</h4>
									<p className="text-muted-foreground">
										Community Activist, 1980-2000
									</p>
								</div>
								<div className="bg-muted rounded-lg p-4 flex flex-col items-center text-center">
									<Avatar className="w-16 h-16 mb-2">
										<AvatarImage
											src="/placeholder-user.jpg"
											alt="Jane Smith"
										/>
										<AvatarFallback>JS</AvatarFallback>
									</Avatar>
									<h4 className="text-lg font-semibold">
										Jane Smith
									</h4>
									<p className="text-muted-foreground">
										Youth Program Coordinator, 1990-2015
									</p>
								</div>
								<div className="bg-muted rounded-lg p-4 flex flex-col items-center text-center">
									<Avatar className="w-16 h-16 mb-2">
										<AvatarImage
											src="/placeholder-user.jpg"
											alt="Michael Lee"
										/>
										<AvatarFallback>ML</AvatarFallback>
									</Avatar>
									<h4 className="text-lg font-semibold">
										Michael Lee
									</h4>
									<p className="text-muted-foreground">
										Volunteer Coordinator, 2005-present
									</p>
								</div>
								<div className="bg-muted rounded-lg p-4 flex flex-col items-center text-center">
									<Avatar className="w-16 h-16 mb-2">
										<AvatarImage
											src="/placeholder-user.jpg"
											alt="Emily Chen"
										/>
										<AvatarFallback>EC</AvatarFallback>
									</Avatar>
									<h4 className="text-lg font-semibold">
										Emily Chen
									</h4>
									<p className="text-muted-foreground">
										Community Organizer, 2010-present
									</p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
				<div className="container px-4 md:px-6">
					<h3 className="text-2xl font-bold tracking-tighter mb-4">
						Photo Gallery
					</h3>
					<div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
						<img
							src="/placeholder.svg"
							width={300}
							height={200}
							alt="Community Center"
							className="rounded-lg object-cover"
							style={{
								aspectRatio: "300/200",
								objectFit: "cover",
							}}
						/>
						<img
							src="/placeholder.svg"
							width={300}
							height={200}
							alt="Community Garden"
							className="rounded-lg object-cover"
							style={{
								aspectRatio: "300/200",
								objectFit: "cover",
							}}
						/>
						<img
							src="/placeholder.svg"
							width={300}
							height={200}
							alt="Community Event"
							className="rounded-lg object-cover"
							style={{
								aspectRatio: "300/200",
								objectFit: "cover",
							}}
						/>
						<img
							src="/placeholder.svg"
							width={300}
							height={200}
							alt="Community Mural"
							className="rounded-lg object-cover"
							style={{
								aspectRatio: "300/200",
								objectFit: "cover",
							}}
						/>
						<img
							src="/placeholder.svg"
							width={300}
							height={200}
							alt="Community Gathering"
							className="rounded-lg object-cover"
							style={{
								aspectRatio: "300/200",
								objectFit: "cover",
							}}
						/>
						<img
							src="/placeholder.svg"
							width={300}
							height={200}
							alt="Community Celebration"
							className="rounded-lg object-cover"
							style={{
								aspectRatio: "300/200",
								objectFit: "cover",
							}}
						/>
						<img
							src="/placeholder.svg"
							width={300}
							height={200}
							alt="Community Volunteers"
							className="rounded-lg object-cover"
							style={{
								aspectRatio: "300/200",
								objectFit: "cover",
							}}
						/>
						<img
							src="/placeholder.svg"
							width={300}
							height={200}
							alt="Community Outreach"
							className="rounded-lg object-cover"
							style={{
								aspectRatio: "300/200",
								objectFit: "cover",
							}}
						/>
					</div>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32">
				<div className="container px-4 md:px-6">
					<h3 className="text-2xl font-bold tracking-tighter mb-4">
						Impact Stories
					</h3>
					<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
						<Card className="bg-muted p-4">
							<CardHeader>
								<CardTitle>Empowering Youth</CardTitle>
							</CardHeader>
							<CardContent>
								<p className="text-muted-foreground">
									Read how our community center&apos;s youth
									programs have transformed the lives of local
									teenagers, providing them with mentorship,
									skills, and opportunities to thrive.
								</p>
							</CardContent>
							<CardFooter>
								<Link
									href="#"
									className="inline-flex items-center gap-2"
									prefetch={false}
								>
									<span>Read More</span>
									<ArrowRightIcon className="h-4 w-4" />
								</Link>
							</CardFooter>
						</Card>
						<Card className="bg-muted p-4">
							<CardHeader>
								<CardTitle>Fostering Inclusivity</CardTitle>
							</CardHeader>
							<CardContent>
								<p className="text-muted-foreground">
									Discover how our community center has become
									a hub for diverse groups, promoting
									understanding, acceptance, and belonging.
								</p>
							</CardContent>
							<CardFooter>
								<Link
									href="#"
									className="inline-flex items-center gap-2"
									prefetch={false}
								>
									<span>Read More</span>
									<ArrowRightIcon className="h-4 w-4" />
								</Link>
							</CardFooter>
						</Card>
						<Card className="bg-muted p-4">
							<CardHeader>
								<CardTitle>
									Preserving Cultural Heritage
								</CardTitle>
							</CardHeader>
							<CardContent>
								<p className="text-muted-foreground">
									Learn how our community center has played a
									vital role in preserving the rich cultural
									heritage of the neighborhood through various
									programs and initiatives.
								</p>
							</CardContent>
							<CardFooter>
								<Link
									href="#"
									className="inline-flex items-center gap-2"
									prefetch={false}
								>
									<span>Read More</span>
									<ArrowRightIcon className="h-4 w-4" />
								</Link>
							</CardFooter>
						</Card>
					</div>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
				<div className="container px-4 md:px-6">
					<h3 className="text-2xl font-bold tracking-tighter mb-4">
						Community Voices
					</h3>
					<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
						<Card className="bg-background p-4">
							<CardHeader>
								<Avatar className="w-12 h-12">
									<AvatarImage
										src="/placeholder-user.jpg"
										alt="John Doe"
									/>
									<AvatarFallback>JD</AvatarFallback>
								</Avatar>
								<div className="ml-2">
									<h4 className="text-lg font-semibold">
										John Doe
									</h4>
									<p className="text-muted-foreground">
										Community Member
									</p>
								</div>
							</CardHeader>
							<CardContent>
								<p className="text-muted-foreground">
									&quot;The community center has been a
									lifeline for my family.\n The programs and
									resources available have truly made a\n
									difference in our lives.&quot;
								</p>
							</CardContent>
						</Card>
						<Card className="bg-background p-4">
							<CardHeader>
								<Avatar className="w-12 h-12">
									<AvatarImage
										src="/placeholder-user.jpg"
										alt="Jane Smith"
									/>
									<AvatarFallback>JS</AvatarFallback>
								</Avatar>
								<div className="ml-2">
									<h4 className="text-lg font-semibold">
										Jane Smith
									</h4>
									<p className="text-muted-foreground">
										Community Volunteer
									</p>
								</div>
							</CardHeader>
							<CardContent>
								<p className="text-muted-foreground">
									&quot;Volunteering at the community center
									has been an incredibly\n rewarding
									experience. I&apos;ve met so many wonderful
									people and\n feel like I&apos;m making a
									real difference.&quot;
								</p>
							</CardContent>
						</Card>
						<Card className="bg-background p-4">
							<CardHeader>
								<Avatar className="w-12 h-12">
									<AvatarImage
										src="/placeholder-user.jpg"
										alt="Michael Lee"
									/>
									<AvatarFallback>ML</AvatarFallback>
								</Avatar>
								<div className="ml-2">
									<h4 className="text-lg font-semibold">
										Michael Lee
									</h4>
									<p className="text-muted-foreground">
										Community Leader
									</p>
								</div>
							</CardHeader>
							<CardContent>
								<p className="text-muted-foreground">
									&quot;The community center has been the
									heart and soul of our\n neighborhood for
									decades. It&apos;s a place where people
									come\n together, support one another, and
									make a real difference.&quot;
								</p>
							</CardContent>
						</Card>
					</div>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32">
				<div className="container px-4 md:px-6">
					<h3 className="text-2xl font-bold tracking-tighter mb-4">
						Find Our Facilities
					</h3>
					<div className="rounded-lg bg-muted p-6">
						<div className="grid grid-cols-1 md:grid-cols-2 gap-6">
							<div>
								<h4 className="text-lg font-semibold mb-2">
									Community Center
								</h4>
								<p className="text-muted-foreground mb-4">
									123 Main Street, Anytown USA
								</p>
								<Link
									href="#"
									className="inline-flex items-center gap-2 bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium hover:bg-primary/90"
									prefetch={false}
								>
									<MapPinIcon className="h-4 w-4" />
									<span>Get Directions</span>
								</Link>
							</div>
							<div>
								<h4 className="text-lg font-semibold mb-2">
									Community Garden
								</h4>
								<p className="text-muted-foreground mb-4">
									456 Oak Avenue, Anytown USA
								</p>
								<Link
									href="#"
									className="inline-flex items-center gap-2 bg-primary px-4 py-2 rounded-md text-primary-foreground font-medium hover:bg-primary/90"
									prefetch={false}
								>
									<MapPinIcon className="h-4 w-4" />
									<span>Get Directions</span>
								</Link>
							</div>
						</div>
					</div>
				</div>
			</section>
		</div>
	);
}

function ArrowRightIcon(
	props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M5 12h14" />
			<path d="m12 5 7 7-7 7" />
		</svg>
	);
}

function MapPinIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
			<circle cx="12" cy="10" r="3" />
		</svg>
	);
}
