/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/grzeUZUqxwW
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Image from "next/image";
import Link from "next/link";

export function Footer() {
	return (
		<footer className="bg-muted py-12 w-full">
			<div className="container max-w-7xl grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
				<div className="flex flex-col items-start gap-4">
					<Link href="#" prefetch={false}>
						<Image
							src="/logo.png"
							alt="Acme Inc"
							width={128}
							height={128}
						/>
					</Link>
					<p className="text-muted-foreground">
						Acme Inc is a leading provider of innovative solutions
						for businesses of all sizes. Our mission is to empower
						our clients with the tools and technologies they need to
						succeed in the digital age.
					</p>
				</div>
				<div className="grid gap-1">
					<h3 className="font-semibold">Navigation</h3>
					<Link href="#" prefetch={false}>
						Home
					</Link>
					<Link href="#" prefetch={false}>
						About
					</Link>
					<Link href="#" prefetch={false}>
						Services
					</Link>
					<Link href="#" prefetch={false}>
						Contact
					</Link>
				</div>
				<div className="grid gap-1">
					<h3 className="font-semibold">Products</h3>
					<Link href="#" prefetch={false}>
						Category A
					</Link>
					<Link href="#" prefetch={false}>
						Category B
					</Link>
					<Link href="#" prefetch={false}>
						Category C
					</Link>
					<Link href="#" prefetch={false}>
						Category D
					</Link>
				</div>
				<div className="grid gap-1">
					<h3 className="font-semibold">Resources</h3>
					<Link href="#" prefetch={false}>
						Blog
					</Link>
					<Link href="#" prefetch={false}>
						Documentation
					</Link>
					<Link href="#" prefetch={false}>
						Support
					</Link>
					<Link href="#" prefetch={false}>
						Community
					</Link>
				</div>
			</div>
			<div className="container max-w-7xl mt-8 text-center text-muted-foreground">
				<p>
					&copy; {new Date().getFullYear()} HERP. All rights reserved.
				</p>
				<p>
					Website designed, created, and donated by{" "}
					<Link
						href={"https://maesela.tech"}
						className="font-semibold underline"
					>
						Maesela
					</Link>{" "}
					and{" "}
					<Link href={""} className="font-semibold underline">
						Lungile
					</Link>{" "}
					on behalf of the{" "}
					<Link
						href={"https://www.uct.ac.za"}
						className="font-semibold underline"
					>
						University of Cape Town (UCT)
					</Link>{" "}
					for HERP.
				</p>
			</div>
		</footer>
	);
}
