/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rfsvqJ6l6hu
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
	Card,
	CardHeader,
	CardTitle,
	CardContent,
	CardFooter,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

export function GetInvolved() {
	return (
		<div className="flex flex-col min-h-[100dvh]">
			<main className="flex-1">
				<section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
					<div className="container px-4 md:px-6">
						<div className="flex flex-col items-center justify-center space-y-4 text-center">
							<div className="space-y-2">
								<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
									Get Involved
								</h2>
								<p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
									There are many ways you can support our
									mission and make a difference in your
									community.
								</p>
							</div>
						</div>
					</div>
				</section>
				<section className="flex items-center justify-center text-center w-full py-12 md:py-24 lg:py-32">
					<div className="container px-4 md:px-6 space-y-6">
						<div className="">
							<div className="space-y-2">
								<div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
									Volunteer Opportunities
								</div>
								<h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
									Join Our Volunteer Team
								</h2>
								<p className="max-w-[100%] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed px-[10%]">
									We have a variety of volunteer roles
									available to support our programs and
									initiatives. Learn more about how you can
									get involved.
								</p>
								<div className="grid gap-4 py-6 sm:grid-cols-2 md:grid-cols-3">
									<Card className="p-6 rounded-lg">
										<CardHeader>
											<CardTitle>
												Event Coordinator
											</CardTitle>
										</CardHeader>
										<CardContent>
											<p className="text-muted-foreground text-left">
												Help plan and execute our
												community events, from
												fundraisers to awareness
												campaigns.
											</p>
										</CardContent>
										<CardFooter>
											<Link
												href="#"
												className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
												prefetch={false}
											>
												Apply Now
											</Link>
										</CardFooter>
									</Card>
									<Card className="p-6 rounded-lg">
										<CardHeader>
											<CardTitle className="text-left">
												Outreach Specialist
											</CardTitle>
										</CardHeader>
										<CardContent>
											<p className="text-muted-foregroundtext-left text-left">
												Connect with local organizations
												and community members to spread
												awareness and build
												partnerships.
											</p>
										</CardContent>
										<CardFooter>
											<Link
												href="#"
												className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
												prefetch={false}
											>
												Apply Now
											</Link>
										</CardFooter>
									</Card>
									<Card className="p-6 rounded-lg">
										<CardHeader>
											<CardTitle className="text-left">
												Administrative Assistant
											</CardTitle>
										</CardHeader>
										<CardContent>
											<p className="text-muted-foreground text-left">
												Support our team with day-to-day
												tasks, data entry, and general
												office duties.
											</p>
										</CardContent>
										<CardFooter>
											<Link
												href="#"
												className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
												prefetch={false}
											>
												Apply Now
											</Link>
										</CardFooter>
									</Card>
								</div>
							</div>
						</div>
						<div className="space-y-2 mt-3">
							<div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
								Funders & Partners
							</div>
							<h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
								Our Supporters
							</h2>
							<p className="max-w-[100%] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed px-[10%]">
								We&apos;re grateful for the generous support of
								our funders and partners who help us achieve our
								mission.
							</p>
							<div className="grid grid-cols-2 gap-4 py-6 sm:grid-cols-4">
								<div className="flex flex-col items-center justify-center p-4 bg-background rounded-full">
									<img
										src="/placeholder.svg"
										width="80"
										height="80"
										alt="Partner Logo"
										className="aspect-square object-contain"
									/>
									<p className="text-sm font-medium mt-2">
										Partner Organization
									</p>
								</div>
								<div className="flex flex-col items-center justify-center p-4 bg-background rounded-full">
									<img
										src="/placeholder.svg"
										width="80"
										height="80"
										alt="Funder Logo"
										className="aspect-square object-contain"
									/>
									<p className="text-sm font-medium mt-2">
										Funding Organization
									</p>
								</div>
								<div className="flex flex-col items-center justify-center p-4 bg-background rounded-full">
									<img
										src="/placeholder.svg"
										width="80"
										height="80"
										alt="Partner Logo"
										className="aspect-square object-contain"
									/>
									<p className="text-sm font-medium mt-2">
										Partner Organization
									</p>
								</div>
								<div className="flex flex-col items-center justify-center p-4 bg-background rounded-full">
									<img
										src="/placeholder.svg"
										width="80"
										height="80"
										alt="Funder Logo"
										className="aspect-square object-contain"
									/>
									<p className="text-sm font-medium mt-2">
										Funding Organization
									</p>
								</div>
							</div>
						</div>
					</div>
				</section>
				<section className="w-full py-12 md:py-24 lg:py-32 bg-muted">
					<div className="container px-4 md:px-6">
						<div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
							<div>
								<div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
									Contact Us
								</div>
								<h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
									Get in Touch
								</h2>
								<p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
									Have a question or want to learn more? Fill
									out the form below and we&apos;ll get back
									to you as soon as possible.
								</p>
								<form className="grid gap-4 py-6">
									<div className="grid gap-2">
										<Label htmlFor="name">Name</Label>
										<Input
											id="name"
											placeholder="Enter your name"
										/>
									</div>
									<div className="grid gap-2">
										<Label htmlFor="email">Email</Label>
										<Input
											id="email"
											type="email"
											placeholder="Enter your email"
										/>
									</div>
									<div className="grid gap-2">
										<Label htmlFor="message">Message</Label>
										<Textarea
											id="message"
											placeholder="Enter your message"
										/>
									</div>
									<Button type="submit" className="mt-2">
										Submit
									</Button>
								</form>
							</div>
							<div>
								<div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">
									Share Your Story
								</div>
								<h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
									Tell Us Your Story
								</h2>
								<p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
									We&apos;d love to hear how our organization
									has impacted your life or your community.
									Share your story with us.
								</p>
								<form className="grid gap-4 py-6">
									<div className="grid gap-2">
										<Label htmlFor="name">Name</Label>
										<Input
											id="name"
											placeholder="Enter your name"
										/>
									</div>
									<div className="grid gap-2">
										<Label htmlFor="email">Email</Label>
										<Input
											id="email"
											type="email"
											placeholder="Enter your email"
										/>
									</div>
									<div className="grid gap-2">
										<Label htmlFor="story">
											Your Story
										</Label>
										<Textarea
											id="story"
											placeholder="Share your story with us"
										/>
									</div>
									<Button type="submit" className="mt-2">
										Submit
									</Button>
								</form>
							</div>
						</div>
					</div>
				</section>
				<section className="w-full py-12 md:py-24 lg:py-32 bg-primary text-primary-foreground">
					<div className="container px-4 md:px-6">
						<div className="flex flex-col items-center justify-center space-y-4 text-center">
							<div className="space-y-2">
								<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
									Support Our Mission
								</h2>
								<p className="max-w-[900px] text-primary-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
									Your financial contribution can help us
									continue our important work in the
									community. Donate today to make a
									difference.
								</p>
							</div>
							<Link
								href="#"
								className="inline-flex h-10 items-center justify-center rounded-md bg-primary-foreground px-8 text-sm font-medium text-primary shadow transition-colors hover:bg-primary-foreground/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Donate Now
							</Link>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}

function MountainIcon(props) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m8 3 4 8 5-5 5 15H2L8 3z" />
		</svg>
	);
}
