/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/SgtVUGhOn7C
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Eczar } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

eczar({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";

export function GetInvolvedCards() {
	return (
		<section
			id="GetInvolved"
			className="w-full py-6 md:py-12 lg:py-16 bg-secondary"
		>
			<div className="container px-4 md:px-6">
				<div className="space-y-4 text-center">
					<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
						Get Involved
					</h2>
					<p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
						There are many ways you can support our non-profit
						organization and make a difference in our community.
						Explore the volunteer opportunities below and find the
						one that best fits your interests and skills.
					</p>
				</div>
				<div className="mt-10 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
					<div className="rounded-lg border bg-background p-6 shadow-sm">
						<h3 className="text-lg font-semibold">
							Fundraising Events
						</h3>
						<p className="mt-2 text-muted-foreground">
							Help us organize and staff our annual fundraising
							events, such as galas, auctions, and charity runs.
							Your support will help us raise crucial funds to
							support our programs.
						</p>
						<div className="mt-4">
							<Link
								href="#"
								className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Sign Up
							</Link>
						</div>
					</div>
					<div className="rounded-lg border bg-background p-6 shadow-sm">
						<h3 className="text-lg font-semibold">
							Community Outreach
						</h3>
						<p className="mt-2 text-muted-foreground">
							Join our team of volunteers who visit local schools,
							community centers, and senior homes to raise
							awareness about our organization and the services we
							provide.
						</p>
						<div className="mt-4">
							<Link
								href="#"
								className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Learn More
							</Link>
						</div>
					</div>
					<div className="rounded-lg border bg-background p-6 shadow-sm">
						<h3 className="text-lg font-semibold">
							Administrative Support
						</h3>
						<p className="mt-2 text-muted-foreground">
							Lend your administrative skills to help us with
							tasks like data entry, filing, and office
							organization. Your support will ensure our team can
							focus on our core mission.
						</p>
						<div className="mt-4">
							<Link
								href="#"
								className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Sign Up
							</Link>
						</div>
					</div>
					<div className="rounded-lg border bg-background p-6 shadow-sm">
						<h3 className="text-lg font-semibold">
							Mentorship Program
						</h3>
						<p className="mt-2 text-muted-foreground">
							Become a mentor to one of the youth in our
							community. Help them develop essential life skills
							and provide guidance as they navigate their personal
							and academic journeys.
						</p>
						<div className="mt-4">
							<Link
								href="#"
								className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Learn More
							</Link>
						</div>
					</div>
					<div className="rounded-lg border bg-background p-6 shadow-sm">
						<h3 className="text-lg font-semibold">
							Food Bank Assistance
						</h3>
						<p className="mt-2 text-muted-foreground">
							Help us sort, package, and distribute food to
							families in need. Your time and effort will make a
							direct impact on addressing food insecurity in our
							community.
						</p>
						<div className="mt-4">
							<Link
								href="#"
								className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Sign Up
							</Link>
						</div>
					</div>
					<div className="rounded-lg border bg-background p-6 shadow-sm">
						<h3 className="text-lg font-semibold">
							Advocacy and Awareness
						</h3>
						<p className="mt-2 text-muted-foreground">
							Help us raise awareness about the important issues
							we address and advocate for policy changes that
							support our mission. Your voice can make a real
							difference.
						</p>
						<div className="mt-4">
							<Link
								href="#"
								className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
								prefetch={false}
							>
								Learn More
							</Link>
						</div>
					</div>
				</div>
			</div>
		</section>
	);
}
