"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LrES2IZeJb0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import React from "react";
import { homePageModel } from "@/lib/cms";
import { CONTENT_TYPE_IDS } from "@/lib/cms";

export function Hero() {
	const [state, setState] = React.useState<homePageModel | null>(null);

	React.useEffect(() => {
		const apiUrl = new URL('/api/cms', window.location.origin);
		const params = new URLSearchParams({
			contentTypeId: CONTENT_TYPE_IDS.HOME,
			limit: '1',
			// You can add more parameters here if needed
		});
		apiUrl.search = params.toString();

		fetch(apiUrl.toString())
			.then(response => response.json())
			.then((data: homePageModel) => {
				if (data) {
					setState(data);
				}
			})
			.catch(error => console.error('Error fetching data:', error));
	}, []);

	return (
		<section
			className="relative w-full h-[80vh] flex items-center justify-center bg-cover bg-center bg-no-repeat"
			style={{ backgroundImage: state?.heroImage ? `url(${state.heroImage})` : "" }}
		>
			<div className="absolute inset-0 bg-black/50 z-0" />
			<div className="relative z-10 text-center max-w-3xl px-6">
				<h1 className="text-4xl sm:text-6xl font-bold text-white mb-4">
					{state?.heroTitle}
				</h1>
				<p className="text-lg sm:text-xl text-white mb-8">
					{state?.heroDescription}
				</p>
				<Link
					href={state?.buttonLink || ""}
					className="inline-flex h-12 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
					prefetch={false}
				>
					{state?.buttonText}
				</Link>
			</div>
		</section>
	);
}