"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LrES2IZeJb0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import React from "react";
import { HomePageModel, CONTENT_TYPE_IDS } from "@/lib/cms";
import { useQuery } from "@tanstack/react-query";
import { getDataFromCMS } from "@/lib/query-functions";
import { LoadingIndicatorComponent } from "../loading-indicator";

export function Hero() {
	// Queries
	const query = useQuery<HomePageModel | null>({
		queryKey: ["homePageData"],
		queryFn: () => getDataFromCMS(CONTENT_TYPE_IDS.HOME),
	});

	if (query.isLoading)
		return (
			<div>
				<LoadingIndicatorComponent />
			</div>
		); // Handle loading state
	if (query.isError)
		return <div>Error fetching data: {query.error.message}</div>; // Handle error state

	return (
		<section
			className="relative w-full h-[80vh] flex items-center justify-center bg-cover bg-center bg-no-repeat"
			style={{
				backgroundImage: query.data?.heroImage
					? `url(${query.data.heroImage})`
					: "",
			}}
		>
			<div className="absolute inset-0 bg-black/50 z-0" />
			<div className="relative z-10 text-center max-w-3xl px-6">
				<h1 className="text-4xl sm:text-6xl font-bold text-white mb-4">
					{query.data?.heroTitle}
				</h1>
				<p className="text-lg sm:text-xl text-white mb-8">
					{query.data?.heroDescription}
				</p>
				<Link
					href={query.data?.buttonLink || ""}
					className="inline-flex h-12 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
					prefetch={false}
				>
					{query.data?.buttonText}
				</Link>
			</div>
		</section>
	);
}
