/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NjexvSzi7XX
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Cabin } from 'next/font/google'
import { Archivo } from 'next/font/google'

cabin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { CommunityCards } from "./community-cards";

export function OurCommunities() {
	return (
		<div className="flex flex-col min-h-[100dvh]">
			<main className="flex-1">
				<section className="w-full py-6">
					<div className="container px-4 md:px-6">
						<div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
							<div className="flex flex-col justify-center space-y-4">
								<div className="space-y-2">
									<h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none">
										Empowering Diverse Communities
									</h1>
									<p className="max-w-[600px] text-muted-foreground md:text-xl">
										At Acme NPO, we are dedicated to
										supporting and uplifting a wide range of
										communities, each with unique needs and
										aspirations. Our mission is to create
										positive change and foster a more
										inclusive and equitable society.
									</p>
								</div>
							</div>
							<img
								src="/placeholder.svg"
								width="550"
								height="550"
								alt="Hero"
								className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
							/>
						</div>
					</div>
				</section>
				<section className="w-full md:py-24 lg:py-32">
					<div className="container px-4 md:px-6">
						<div className="flex flex-col items-center justify-center text-center">
							<div className="space-y-2">
								<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
									Our Diverse Communities
								</h2>
								<p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
									Acme NPO works closely with a wide range of
									communities, each with unique needs and
									challenges. Explore the communities we serve
									and learn more about our collaborative
									efforts.
								</p>
							</div>
						</div>
						<div>
							<CommunityCards />
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
