/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wUiBVU28nEw
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import {
	Carousel,
	CarouselContent,
	CarouselItem,
	CarouselPrevious,
	CarouselNext,
} from "@/components/ui/carousel";
import { Card } from "@/components/ui/card";
import { JSX, SVGProps } from "react";

export function Partnerships() {
	return (
		<section className="w-full py-12 md:py-16 lg:py-20">
			<div className="container">
				<div className="flex flex-col items-center justify-center space-y-4 text-center">
					<h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
						Our Partners
					</h2>
					<p className="max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
						{
							"We're proud to work with these amazing organizations to make a positive impact."
						}
					</p>
				</div>
				<div className="mt-10 md:mt-12 lg:mt-16 flex justify-center">
					<Carousel
						className="w-4/5 max-w-6xl"
						opts={{
							loop: true,
						}}
					>
						<CarouselContent>
							<CarouselItem className="md:basis-1/3">
								<Card className="p-6 flex flex-col items-center justify-center gap-4">
									<img
										src="/placeholder.svg"
										width={100}
										height={50}
										alt="Partner Logo"
										className="aspect-[2/1] overflow-hidden rounded-full object-contain object-center"
									/>
									<h3 className="text-lg font-semibold">
										Partner Name
									</h3>
									<p className="text-muted-foreground text-sm">
										{
											"Short description of partner's involvement"
										}
									</p>
								</Card>
							</CarouselItem>
							<CarouselItem className="md:basis-1/3">
								<Card className="p-6 flex flex-col items-center justify-center gap-4">
									<img
										src="/placeholder.svg"
										width={100}
										height={50}
										alt="Partner Logo"
										className="aspect-[2/1] overflow-hidden rounded-full object-contain object-center"
									/>
									<h3 className="text-lg font-semibold">
										Partner Name
									</h3>
									<p className="text-muted-foreground text-sm">
										{
											"Short description of partner's involvement"
										}
									</p>
								</Card>
							</CarouselItem>
							<CarouselItem className="md:basis-1/3">
								<Card className="p-6 flex flex-col items-center justify-center gap-4">
									<img
										src="/placeholder.svg"
										width={100}
										height={50}
										alt="Partner Logo"
										className="aspect-[2/1] overflow-hidden rounded-full object-contain object-center"
									/>
									<h3 className="text-lg font-semibold">
										Partner Name
									</h3>
									<p className="text-muted-foreground text-sm">
										{
											"Short description of partner's involvement"
										}
									</p>
								</Card>
							</CarouselItem>
						</CarouselContent>
						<CarouselPrevious>
							<ChevronLeftIcon className="h-6 w-6 text-primary-foreground" />
						</CarouselPrevious>
						<CarouselNext>
							<ChevronRightIcon className="h-6 w-6 text-primary-foreground" />
						</CarouselNext>
					</Carousel>
				</div>
			</div>
		</section>
	);
}

function ChevronLeftIcon(
	props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m15 18-6-6 6-6" />
		</svg>
	);
}

function ChevronRightIcon(
	props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>
) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m9 18 6-6-6-6" />
		</svg>
	);
}
