/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xw3dgX3yDrc
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { JSX, SVGProps } from "react";

export function Values() {
	return (
		<div>
			<section className="w-full py-4 md:py-4 bg-background mb-12">
				<div className="container px-4 md:px-6 grid gap-12 items-center">
					<Card className="bg-card p-8 rounded-lg shadow-lg w-full">
						<CardHeader>
							<CardTitle className="text-3xl md:text-4xl font-bold">
								Our Story
							</CardTitle>
						</CardHeader>
						<CardContent className="space-y-4">
							<p className="text-muted-foreground">
								Founded in 2010, our non-profit organization has
								been committed to making a lasting difference in
								the communities we serve. With a focus on
								sustainable development and empowerment, we have
								implemented various initiatives to address the
								pressing needs of those facing poverty, lack of
								education, and limited access to healthcare.
							</p>
							<p className="text-muted-foreground">
								Through collaborative partnerships and the
								dedication of our team, we have been able to
								expand our reach and impact over the years. Our
								mission is to continue to grow and adapt to the
								evolving needs of the communities we serve,
								always striving to create a more just and
								equitable world.
							</p>
						</CardContent>
					</Card>
					<div className="grid grid-cols-1 gap-6 w-full sm:grid-cols-2">
						<Card className="bg-card p-6 rounded-lg shadow-lg flex flex-col items-center gap-4">
							<UsersIcon className="w-12 h-12 text-primary" />
							<h3 className="text-xl font-semibold">
								Empowered Individuals
							</h3>
							<p className="text-muted-foreground text-center">
								We empower individuals to become self-sufficient
								and achieve their full potential.
							</p>
						</Card>
						<Card className="bg-card p-6 rounded-lg shadow-lg flex flex-col items-center gap-4">
							<HeartIcon className="w-12 h-12 text-primary" />
							<h3 className="text-xl font-semibold">
								Compassionate Support
							</h3>
							<p className="text-muted-foreground text-center">
								We provide compassionate support to those in
								need, addressing their unique challenges.
							</p>
						</Card>
						<Card className="bg-card p-6 rounded-lg shadow-lg flex flex-col items-center gap-4">
							<LeafIcon className="w-12 h-12 text-primary" />
							<h3 className="text-xl font-semibold">
								Sustainable Impact
							</h3>
							<p className="text-muted-foreground text-center">
								Our initiatives are designed to create lasting,
								sustainable change in the communities we serve.
							</p>
						</Card>
						<Card className="bg-card p-6 rounded-lg shadow-lg flex flex-col items-center gap-4">
							<TargetIcon className="w-12 h-12 text-primary" />
							<h3 className="text-xl font-semibold">
								Focused Goals
							</h3>
							<p className="text-muted-foreground text-center">
								We have clearly defined goals and a strategic
								plan to achieve our mission.
							</p>
						</Card>
					</div>
				</div>
			</section>
		</div>
	);
}

function HeartIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
		</svg>
	);
}

function LeafIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10Z" />
			<path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12" />
		</svg>
	);
}

function TargetIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<circle cx="12" cy="12" r="10" />
			<circle cx="12" cy="12" r="6" />
			<circle cx="12" cy="12" r="2" />
		</svg>
	);
}

function UsersIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
	return (
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
			<circle cx="9" cy="7" r="4" />
			<path d="M22 21v-2a4 4 0 0 0-3-3.87" />
			<path d="M16 3.13a4 4 0 0 1 0 7.75" />
		</svg>
	);
}
